---
name: Changed Files
description: Determine which files have changed since the last workflow run
outputs:
  json:
    description: List of files that changed as a JSON array
  text:
    description: List of files that changed as plain text
runs:
  using: node12
  main: dist/main.js
