name: Main

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci

      - run: npm t
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run colpal/actions-changed-files
        id: changed
        uses: ./

      - name: Output all as text
        run: echo '${{ steps.changed.outputs.all }}'

      - name: Output modified as text
        run: echo '${{ steps.changed.outputs.modified }}'

      - name: Output deleted as text
        run: echo '${{ steps.changed.outputs.deleted }}'

      - name: Output added as text
        run: echo '${{ steps.changed.outputs.added }}'

      - name: Output as JSON
        run: echo '${{ steps.changed.outputs.json }}'
