---
name: Main

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Run colpal/actions-changed-files
        id: changed
        uses: ./

      - name: Output as Text
        run: echo '${{ steps.changed.outputs.text }}'

      - name: Output as JSON
        run: echo '${{ steps.changed.outputs.json }}'
