---
name: Main

'on':
  push:
  pull_Request:
    types: [opened, synchronize, reopened, closed]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run colpal/actions-changed-files
        id: changed
        uses: ./

      - name: Output all as text
        run: echo '${{ steps.changed.outputs.all }}'

      - name: Output modified as text
        run: echo '${{ steps.changed.outputs.modified }}'

      - name: Output deleted as text
        run: echo '${{ steps.changed.outputs.deleted }}'

      - name: Output added as text
        run: echo '${{ steps.changed.outputs.added }}'

      - name: Output as JSON
        run: echo '${{ steps.changed.outputs.json }}'
